version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    volumes:
      - data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  data:

networks:
  elastic: